# Generated by Django 5.2.1 on 2025-05-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='current_status',
            field=models.CharField(choices=[('RECEIVED_FRONT_DESK', 'Received at Front Desk'), ('SENT_TO_LAB', 'Sent to Lab'), ('TESTING_IN_PROGRESS', 'Testing in Progress'), ('RESULTS_ENTERED', 'Results Entered'), ('REVIEW_PENDING', 'Review Pending'), ('REPORT_APPROVED', 'Report Approved'), ('REPORT_SENT', 'Report Sent'), ('CANCELLED', 'Cancelled')], default='RECEIVED_FRONT_DESK', max_length=50),
        ),
    ]
