# Generated by Django 5.2.1 on 2025-05-29 12:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_sample_current_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="district",
            field=models.CharField(
                choices=[
                    ("thiruvananthapuram", "Thiruvananthapuram"),
                    ("kollam", "Kollam"),
                    ("pathanamthitta", "Pathanamthitta"),
                    ("alappuzha", "Alappuzha"),
                    ("kottayam", "Kottayam"),
                    ("idukki", "Idukki"),
                    ("ernakulam", "Ernakulam"),
                    ("thrissur", "Thrissur"),
                    ("palakkad", "Palakkad"),
                    ("malappuram", "Malappuram"),
                    ("kozhikode", "Kozhikode"),
                    ("wayanad", "Wayanad"),
                    ("kannur", "Kannur"),
                    ("kasaragod", "Kasaragod"),
                ],
                default="thiruvananthapuram",
                max_length=50,
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pincode",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "PIN code must be 6 digits."
                    ),
                    core.models.validate_kerala_pincode,
                ],
                verbose_name="PIN Code",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street_locality_landmark",
            field=models.CharField(max_length=200, verbose_name="Street / Locality"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="village_town_city",
            field=models.CharField(max_length=100, verbose_name="Village / Town"),
        ),
    ]
