# Generated by Django 5.2.1 on 2025-06-01 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_customer_district_alter_customer_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="display_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Human-readable Sample ID (e.g., WL2025-0001)",
                max_length=20,
                unique=False, # Changed from True
                null=True, # Added
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Primary key UUID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
