# Generated by Django 5.2.1 on 2025-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_populate_sample_display_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="display_id",
            field=models.CharField(
                blank=True,
                default="temp-id",
                editable=False,
                help_text="Human-readable Sample ID (e.g., WL2025-0001)",
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
