# Generated by Django 5.2.1 on 2025-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_sample_display_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="referred_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
