# Generated by Django 5.2.1 on 2025-06-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_sample_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="testparameter",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="testparameter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.testparameter",
            ),
        ),
    ]
