# Generated by Django 5.2.1 on 2025-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_testparameter_category_testparameter_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="district",
            field=models.CharField(
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kollam", "Kollam"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kottayam", "Kottayam"),
                    ("Idukki", "Idukki"),
                    ("Ernakulam", "Ernakulam"),
                    ("Thrissur", "Thrissur"),
                    ("Palakkad", "Palakkad"),
                    ("Malappuram", "Malappuram"),
                    ("Kozhikode", "Kozhikode"),
                    ("Wayanad", "Wayanad"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                ],
                default="thiruvananthapuram",
                max_length=50,
                verbose_name="District",
            ),
        ),
    ]
