# Generated by Django 5.2.1 on 2025-06-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_customer_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="deviations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Any Deviation from Test Methods"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="food_analyst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyzed_samples",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Food Analyst",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="lab_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_samples",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lab Manager",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="quantity_received",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Quantity Received"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="report_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Test Report Number"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_samples",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                default="WATER", max_length=50, verbose_name="Sample Type"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="sampling_location",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Location of Sampling",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="sampling_procedure",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sampling Procedure"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="test_commenced_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Test Commenced On"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="test_completed_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Test Completed On"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="ulr_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ULR Number"
            ),
        ),
        migrations.AddField(
            model_name="testparameter",
            name="discipline",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Discipline"
            ),
        ),
        migrations.AddField(
            model_name="testparameter",
            name="fssai_limit",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FSSAI Limit"
            ),
        ),
        migrations.AddField(
            model_name="testparameter",
            name="group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Group"
            ),
        ),
    ]
