# Generated by Django 5.2.1 on 2025-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sample_deviations_sample_food_analyst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collected_by',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('LABORATORY_PERSON', 'Laboratory Person'), ('GOVERNMENT_DEPT', 'Government Dept')], default='CUSTOMER', max_length=255),
        ),
    ]
