# Generated by Django 5.2.1 on 2025-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_additional_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='customuser_role_idx'),
        ),
    ]
