# Generated by Django 5.2.1 on 2025-12-08 06:28

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_labprofile_signatory_solutions_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kollam", "Kollam"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kottayam", "Kottayam"),
                    ("Idukki", "Idukki"),
                    ("Ernakulam", "Ernakulam"),
                    ("Thrissur", "Thrissur"),
                    ("Palakkad", "Palakkad"),
                    ("Malappuram", "Malappuram"),
                    ("Kozhikode", "Kozhikode"),
                    ("Wayanad", "Wayanad"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                ],
                default="",
                max_length=50,
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pincode",
            field=models.CharField(
                blank=True,
                default="",
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "PIN code must be 6 digits."
                    ),
                    core.models.validate_kerala_pincode,
                ],
                verbose_name="PIN Code",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street_locality_landmark",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Street / Locality"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="village_town_city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Village / Town"
            ),
        ),
    ]
