# Generated by Django 5.2.1 on 2026-03-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_invoice_models_and_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='last_reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reopened At'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_reopened', to=settings.AUTH_USER_MODEL, verbose_name='Last Reopened By'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_reopened_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Last Reopen Reason'),
        ),
        migrations.AddField(
            model_name='sample',
            name='report_revision',
            field=models.PositiveIntegerField(default=1, verbose_name='Report Revision'),
        ),
    ]
