# Generated by Django 5.2.1 on 2026-04-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_customer_options_sample_last_reopened_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lab', 'Lab Technician'), ('frontdesk', 'Front Desk'), ('consultant', 'Consultant'), ('food_analyst', 'Chief Scientific Officer'), ('bio_manager', 'Chief of Quality - Microbiology'), ('chem_manager', 'Chief of Quality - Chemistry'), ('solutions_manager', 'Chief of Solutions - Water Quality')], default='frontdesk', max_length=20),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='signatory_bio_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_bio_manager_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Default Chief of Quality - Microbiology'),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='signatory_chem_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_chem_manager_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Default Chief of Quality - Chemistry'),
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='signatory_food_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_food_analyst_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Default Chief Scientific Officer'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='food_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_samples', to=settings.AUTH_USER_MODEL, verbose_name='Chief Scientific Officer'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_samples', to=settings.AUTH_USER_MODEL, verbose_name='Chief of Quality - Chemistry'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_samples', to=settings.AUTH_USER_MODEL, verbose_name='Chief of Quality - Microbiology'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_source',
            field=models.CharField(choices=[('WELL', 'Well'), ('BOREWELL', 'Borewell'), ('TAP', 'Tap'), ('RIVER', 'River'), ('POND', 'Pond'), ('PRODUCT_WATER', 'Product Water'), ('TREATED_WATER', 'Treated Water'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
