# Generated by Django 5.2.1 on 2026-04-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_customer_options_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['district'], name='customer_district_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pincode'], name='customer_pincode_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_by', 'name'], name='customer_created_name_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['current_status', 'collection_datetime'], name='sample_status_collected_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['customer', 'collection_datetime'], name='sample_customer_collected_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['created_by', 'collection_datetime'], name='sample_created_collected_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['sample', 'test_date'], name='testresult_sample_date_idx'),
        ),
    ]
